#!/bin/bash

## needs fully-qualified name
pushd `dirname $0` > /dev/null
PROJ_HOME=`pwd`/..
popd > /dev/null

SRCDIR="${PROJ_HOME}/src"
SPLATDIR="${PROJ_HOME}/splat"
BUILDDIR="${PROJ_HOME}/build"
LOGSDIR="${PROJ_HOME}/data"
CP="${BUILDDIR}"

export PROJ_HOME
export SPLATDIR
export SRCDIR
export BUILDDIR
export LOGSDIR
export CP