#!/bin/bash

source `dirname $0`/commons

if [ -z "$BUILDDIR" ];
then
    echo "Plese inform name of the subject you want to analyze"
    exit
fi

mkdir -p ${BUILDDIR}

LIBSDIR="${SPLATDIR}/libs"
for x in `ls ${LIBSDIR}/*.jar`;
do
  CP=${x}:${CP}
done

######## compile splat
find "${SPLATDIR}/src" -name "*.java" | \
    xargs javac -cp $CP -d ${BUILDDIR}



