#!/bin/bash

source `dirname $0`/commons

SUBJECT="$1"
MATRIX_FILE_NAME="${LOGSDIR}/matrix-${SUBJECT}.txt"
LOG_FILE_NAME="${LOGSDIR}/log-${SUBJECT}.txt"
DISCRETIZED_MATRIX_FILE_NAME="${LOGSDIR}/discretized-matrix-${SUBJECT}.txt"


if [[ ! -f "${MATRIX_FILE_NAME}" ]];
then
    echo "Could not find file $1"
    exit
fi

if [[ -z ${PROJ_HOME} ]];
then
    echo "Please define variable PROJ_HOME."
    echo "E.g., $> export PROJ_HOME=..."
    exit
fi

if [[ ! -d "${SRCDIR}" ]];
then
    echo "Could not find directory $PROJ_HOME/bin."
    exit
fi


## create build directory if does not exist
mkdir -p ${BUILDDIR}

CLASSPATH="${BUILDDIR}"

## compile
find ${SRCDIR} -name "*.java" | \
    xargs javac -cp ${CLASSPATH} -d ${BUILDDIR}

## generating discretized matrix
TMP="/tmp/discretized.tmp"
cat "${MATRIX_FILE_NAME}" | java -cp ${CLASSPATH} DiscretizeMatrix > ${TMP}

## removing generating discretized matrix
java -cp ${CLASSPATH} UpdateNames "${LOG_FILE_NAME}" "${TMP}" > "${DISCRETIZED_MATRIX_FILE_NAME}"

## discretized matrix
echo "discretized matrix in ${DISCRETIZED_MATRIX_FILE_NAME}"