#!/bin/bash

source `dirname $0`/commons

if [[ ! -f "${1}" ]];
then
    echo "Could not find file $1"
    exit
fi

if [[ -z ${PROJ_HOME} ]];
then
    echo "Please define variable PROJ_HOME."
    echo "E.g., $> export PROJ_HOME=..."
    exit
fi

if [[ ! -d "${SRCDIR}" ]];
then
    echo "Could not find directory $PROJ_HOME/bin."
    exit
fi


## create build directory if does not exist
mkdir -p ${BUILDDIR}

CLASSPATH="${BUILDDIR}"

## compile
find ${SRCDIR} -name "*.java" | \
    xargs javac -cp ${CLASSPATH} -d ${BUILDDIR}

## run
cat $1 | java -cp ${CLASSPATH} DiscretizeMatrix 
